runtime: nodejs20

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  PORT: 8080

# Health check endpoint
handlers:
  - url: /.*
    script: auto

