require("dotenv").config();
const { query } = require("./db");

/**
 * Populate database with 100 popular movies
 */
const popularMovies = [
  { title: "The Shawshank Redemption", year: 1994, genre: "Drama", description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", duration: 142, poster_url: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", trailer_url: "https://www.youtube.com/watch?v=6hB3S9bIaco" },
  { title: "The Godfather", year: 1972, genre: "Crime", description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", duration: 175, poster_url: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", trailer_url: "https://www.youtube.com/watch?v=UaVTIH8mujA" },
  { title: "The Dark Knight", year: 2008, genre: "Action", description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", duration: 152, poster_url: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", trailer_url: "https://www.youtube.com/watch?v=EXeTwQWrcwY" },
  { title: "Pulp Fiction", year: 1994, genre: "Crime", description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", duration: 154, poster_url: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", trailer_url: "https://www.youtube.com/watch?v=s7EdQ4FqbhY" },
  { title: "Forrest Gump", year: 1994, genre: "Drama", description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.", duration: 142, poster_url: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVz6ZX6S9KhQBY5il.jpg", trailer_url: "https://www.youtube.com/watch?v=bLvqoHBptjg" },
  { title: "Inception", year: 2010, genre: "Sci-Fi", description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", duration: 148, poster_url: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg", trailer_url: "https://www.youtube.com/watch?v=YoHD9XEInc0" },
  { title: "The Matrix", year: 1999, genre: "Sci-Fi", description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", duration: 136, poster_url: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", trailer_url: "https://www.youtube.com/watch?v=vKQi3bBA1y8" },
  { title: "Goodfellas", year: 1990, genre: "Crime", description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.", duration: 146, poster_url: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg", trailer_url: "https://www.youtube.com/watch?v=qo5jJ5tWbF4" },
  { title: "Fight Club", year: 1999, genre: "Drama", description: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.", duration: 139, poster_url: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg", trailer_url: "https://www.youtube.com/watch?v=SUXWAEX2jlg" },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, genre: "Fantasy", description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.", duration: 178, poster_url: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkI9kRX45.jpg", trailer_url: "https://www.youtube.com/watch?v=V75dMMIW2B4" },
  { title: "Star Wars: Episode IV - A New Hope", year: 1977, genre: "Sci-Fi", description: "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire.", duration: 121, poster_url: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg", trailer_url: "https://www.youtube.com/watch?v=vZ734NWnAHA" },
  { title: "The Godfather Part II", year: 1974, genre: "Crime", description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.", duration: 202, poster_url: "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FhFdXvXkU0jKZ.jpg", trailer_url: "https://www.youtube.com/watch?v=9O1Iy9od7-A" },
  { title: "The Lord of the Rings: The Return of the King", year: 2003, genre: "Fantasy", description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.", duration: 201, poster_url: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg", trailer_url: "https://www.youtube.com/watch?v=r5X-hFf6Bwo" },
  { title: "Schindler's List", year: 1993, genre: "Drama", description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.", duration: 195, poster_url: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg", trailer_url: "https://www.youtube.com/watch?v=gG22XNhtnoY" },
  { title: "The Lord of the Rings: The Two Towers", year: 2002, genre: "Fantasy", description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman.", duration: 179, poster_url: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg", trailer_url: "https://www.youtube.com/watch?v=LbfMDwc4azU" },
  { title: "The Good, the Bad and the Ugly", year: 1966, genre: "Western", description: "While the Civil War rages between the Union and the Confederacy, three men hunt for the fortune in gold buried in a remote cemetery.", duration: 178, poster_url: "https://image.tmdb.org/t/p/w500/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg", trailer_url: "https://www.youtube.com/watch?v=WCN5JJY_wiA" },
  { title: "The Empire Strikes Back", year: 1980, genre: "Sci-Fi", description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda.", duration: 124, poster_url: "https://image.tmdb.org/t/p/w500/6uBlEXaC4b7kag3OuPC0x5Vc3Fj.jpg", trailer_url: "https://www.youtube.com/watch?v=JNwNXF9Y6kY" },
  { title: "The Prestige", year: 2006, genre: "Mystery", description: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.", duration: 130, poster_url: "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg", trailer_url: "https://www.youtube.com/watch?v=ijXruSzfGEc" },
  { title: "Casablanca", year: 1942, genre: "Romance", description: "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis.", duration: 102, poster_url: "https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSInzqJ5Gab1Wv.jpg", trailer_url: "https://www.youtube.com/watch?v=BkL9l7qovsE" },
  { title: "The Lion King", year: 1994, genre: "Animation", description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", duration: 88, poster_url: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", trailer_url: "https://www.youtube.com/watch?v=4sj1MT05lAA" },
  { title: "Gladiator", year: 2000, genre: "Action", description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", duration: 155, poster_url: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg", trailer_url: "https://www.youtube.com/watch?v=owK1qxDselE" },
  { title: "Titanic", year: 1997, genre: "Romance", description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", duration: 194, poster_url: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", trailer_url: "https://www.youtube.com/watch?v=kVrqfYjkTdQ" },
  { title: "The Departed", year: 2006, genre: "Crime", description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.", duration: 151, poster_url: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQme043qHZmzK3Y.jpg", trailer_url: "https://www.youtube.com/watch?v=iojhqm0JTW4" },
  { title: "The Green Mile", year: 1999, genre: "Drama", description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.", duration: 189, poster_url: "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg", trailer_url: "https://www.youtube.com/watch?v=Ki4haFrqSrw" },
  { title: "Saving Private Ryan", year: 1998, genre: "War", description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", duration: 169, poster_url: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg", trailer_url: "https://www.youtube.com/watch?v=zwhP5b4tD6g" },
  { title: "The Usual Suspects", year: 1995, genre: "Crime", description: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.", duration: 106, poster_url: "https://image.tmdb.org/t/p/w500/jo3Kv1Fz7gPJbT3vZgkT7hYe8UV.jpg", trailer_url: "https://www.youtube.com/watch?v=oiXdPolca5w" },
  { title: "Se7en", year: 1995, genre: "Crime", description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", duration: 127, poster_url: "https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg", trailer_url: "https://www.youtube.com/watch?v=znmZoVkCjpI" },
  { title: "Braveheart", year: 1995, genre: "Drama", description: "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.", duration: 178, poster_url: "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0oww2kq.jpg", trailer_url: "https://www.youtube.com/watch?v=wj0I8xVTV18" },
  { title: "The Shining", year: 1980, genre: "Horror", description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.", duration: 146, poster_url: "https://image.tmdb.org/t/p/w500/9fgh3Ns1iRzlQNYuJyK0ARQZU7w.jpg", trailer_url: "https://www.youtube.com/watch?v=5Cb3ik6zP2I" },
  { title: "The Pianist", year: 2002, genre: "Drama", description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.", duration: 150, poster_url: "https://image.tmdb.org/t/p/w500/iunmxWkOi7TQ9g2X7Ntq4Ipgqat.jpg", trailer_url: "https://www.youtube.com/watch?v=u_jE7-6Uv7E" },
  { title: "Whiplash", year: 2014, genre: "Drama", description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.", duration: 107, poster_url: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg", trailer_url: "https://www.youtube.com/watch?v=7d_jQycdQGo" },
  { title: "Parasite", year: 2019, genre: "Thriller", description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", duration: 132, poster_url: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", trailer_url: "https://www.youtube.com/watch?v=5xH0HfJHsaY" },
  { title: "Get Out", year: 2017, genre: "Horror", description: "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness about their reception of him eventually reaches a boiling point.", duration: 104, poster_url: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg", trailer_url: "https://www.youtube.com/watch?v=sRfnevzM9kQ" },
  { title: "Spirited Away", year: 2001, genre: "Animation", description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.", duration: 125, poster_url: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", trailer_url: "https://www.youtube.com/watch?v=ByXuk9QqQkk" },
  { title: "The Social Network", year: 2010, genre: "Drama", description: "As Harvard student Mark Zuckerberg creates the social networking site that would become Facebook, he is sued by the twins who claimed he stole their idea.", duration: 120, poster_url: "https://image.tmdb.org/t/p/w500/ok5Wh8385Kgblq9MSU4VGvaze4z.jpg", trailer_url: "https://www.youtube.com/watch?v=lB95KLmpLR4" },
  { title: "Citizen Kane", year: 1941, genre: "Drama", description: "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance.", duration: 119, poster_url: "https://image.tmdb.org/t/p/w500/sav0jxhqiH0bPr2vZFU0OjtIoc5.jpg", trailer_url: "https://www.youtube.com/watch?v=8dxh3lwdOFw" },
  { title: "Gone with the Wind", year: 1939, genre: "Romance", description: "A manipulative Southern belle carries on a turbulent affair with a blockade runner during the American Civil War.", duration: 238, poster_url: "https://image.tmdb.org/t/p/w500/4m6s83wYOPjNPDqJT49YI7FfCOj.jpg", trailer_url: "https://www.youtube.com/watch?v=0X94oZgJisI" },
  { title: "Lawrence of Arabia", year: 1962, genre: "Adventure", description: "The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I.", duration: 218, poster_url: "https://image.tmdb.org/t/p/w500/rb2VkQvGkmfzLsh3hY3H8G8vZr.jpg", trailer_url: "https://www.youtube.com/watch?v=zmr1iSG3RTA" },
  { title: "The Wizard of Oz", year: 1939, genre: "Fantasy", description: "Young Dorothy Gale and her dog are swept away by a tornado from their Kansas farm to the magical Land of Oz.", duration: 102, poster_url: "https://image.tmdb.org/t/p/w500/4BT6qfAL4cpl2u7UqmqN0xHba3H.jpg", trailer_url: "https://www.youtube.com/watch?v=PSZxmZmBfnU" },
  { title: "The Graduate", year: 1967, genre: "Comedy", description: "A disillusioned college graduate finds himself torn between his older lover and her daughter.", duration: 106, poster_url: "https://image.tmdb.org/t/p/w500/7gZFl3qUXKf3Y0k1kXXYHdqTkWh.jpg", trailer_url: "https://www.youtube.com/watch?v=Y0h1j2w0FSU" },
  { title: "On the Waterfront", year: 1954, genre: "Drama", description: "An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.", duration: 108, poster_url: "https://image.tmdb.org/t/p/w500/7hGuevAlQfE2jB8q3Z8x6vY9VqP.jpg", trailer_url: "https://www.youtube.com/watch?v=U7fj0NMwvtY" },
  { title: "Singin' in the Rain", year: 1952, genre: "Musical", description: "A silent film production company and cast make a difficult transition to sound.", duration: 103, poster_url: "https://image.tmdb.org/t/p/w500/4gZgXgR0aQzb0z6tJ1W6J3q5J9x.jpg", trailer_url: "https://www.youtube.com/watch?v=D1ZYhVpdXbQ" },
  { title: "Psycho", year: 1960, genre: "Horror", description: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.", duration: 109, poster_url: "https://image.tmdb.org/t/p/w500/81d8oyEFgj7FlxJqSDXWup8lEJV.jpg", trailer_url: "https://www.youtube.com/watch?v=0WtDmbr9xY0" },
  { title: "Jaws", year: 1975, genre: "Thriller", description: "When a killer shark unleashes chaos on a beach community, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.", duration: 124, poster_url: "https://image.tmdb.org/t/p/w500/lxM6t0rY8wMrXb3A7sCxuV3Q9kZ.jpg", trailer_url: "https://www.youtube.com/watch?v=U1fu_sA7XhE" },
  { title: "The Exorcist", year: 1973, genre: "Horror", description: "When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.", duration: 122, poster_url: "https://image.tmdb.org/t/p/w500/4ucLGc1oMB5N20d1lJymco6bXkS.jpg", trailer_url: "https://www.youtube.com/watch?v=YDGw1MTEe8k" },
  { title: "North by Northwest", year: 1959, genre: "Thriller", description: "A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies.", duration: 136, poster_url: "https://image.tmdb.org/t/p/w500/aNV5S3Q8f8X18vBZ6V8u4h4JY5T.jpg", trailer_url: "https://www.youtube.com/watch?v=1nUz8iSdY1o" },
  { title: "The Silence of the Lambs", year: 1991, genre: "Thriller", description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.", duration: 118, poster_url: "https://image.tmdb.org/t/p/w500/rplLJ2hPcRwN52Xauj7kwWr2x07.jpg", trailer_url: "https://www.youtube.com/watch?v=RuX2MQeb8UM" },
  { title: "Alien", year: 1979, genre: "Horror", description: "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.", duration: 117, poster_url: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Vm3MbIV.jpg", trailer_url: "https://www.youtube.com/watch?v=jQ5lPt9edzQ" },
  { title: "The French Connection", year: 1971, genre: "Crime", description: "A pair of NYC cops in the Narcotics Bureau stumble onto a drug smuggling job with a French connection.", duration: 104, poster_url: "https://image.tmdb.org/t/p/w500/5hqbJSFp4jWjXo2vLqQ3Jz3qY5x.jpg", trailer_url: "https://www.youtube.com/watch?v=6bYo6tp3rHE" },
  { title: "Raiders of the Lost Ark", year: 1981, genre: "Adventure", description: "Archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before the Nazis.", duration: 115, poster_url: "https://image.tmdb.org/t/p/w500/ceG9VzoJ4wcn87MTWJ4RDr1kZ2P.jpg", trailer_url: "https://www.youtube.com/watch?v=0xQSIdSRlAk" },
  { title: "Back to the Future", year: 1985, genre: "Sci-Fi", description: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean.", duration: 116, poster_url: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOxjRi0izd.jpg", trailer_url: "https://www.youtube.com/watch?v=qvsgGtivCgs" },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004, genre: "Romance", description: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.", duration: 108, poster_url: "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg", trailer_url: "https://www.youtube.com/watch?v=rb9a00fX28U" },
  { title: "No Country for Old Men", year: 2007, genre: "Crime", description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million in cash near the Rio Grande.", duration: 122, poster_url: "https://image.tmdb.org/t/p/w500/nBZgp3Gx6s7V5o8Y1L0xTdW3Z5x.jpg", trailer_url: "https://www.youtube.com/watch?v=38A__w3eZ4I" },
  { title: "Moonlight", year: 2016, genre: "Drama", description: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.", duration: 111, poster_url: "https://image.tmdb.org/t/p/w500/qAwFbszz0kRyTuXmMeKQZCX3Q2O.jpg", trailer_url: "https://www.youtube.com/watch?v=9NJj12tJzqc" },
  { title: "There Will Be Blood", year: 2007, genre: "Drama", description: "A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.", duration: 158, poster_url: "https://image.tmdb.org/t/p/w500/fa0rd2ICY8s80OhI8pUIVlu0R5C.jpg", trailer_url: "https://www.youtube.com/watch?v=FeSLPEL_PMe" },
  { title: "In the Mood for Love", year: 2000, genre: "Romance", description: "A man and a woman move into neighboring Hong Kong apartments and form a bond when they both suspect their spouses of extramarital activities.", duration: 98, poster_url: "https://image.tmdb.org/t/p/w500/7k3g8Xsh3xWDdKDx0Xv6x7Vxq0Z.jpg", trailer_url: "https://www.youtube.com/watch?v=6N2356XyV5U" },
  { title: "Mulholland Drive", year: 2001, genre: "Mystery", description: "After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers.", duration: 147, poster_url: "https://image.tmdb.org/t/p/w500/tVxGtpcuffcOV7G3Hd4Q32uvR4p.jpg", trailer_url: "https://www.youtube.com/watch?v=jbZJ487oJlY" },
  { title: "The Intouchables", year: 2011, genre: "Comedy", description: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.", duration: 112, poster_url: "https://image.tmdb.org/t/p/w500/4mFsNQubD8Qd2oFm4u1HqXZJ5x.jpg", trailer_url: "https://www.youtube.com/watch?v=34WIbmXkewU" },
  { title: "Rosemary's Baby", year: 1968, genre: "Horror", description: "A young couple moves into an apartment only to be surrounded by peculiar neighbors and occurrences.", duration: 137, poster_url: "https://image.tmdb.org/t/p/w500/6SPFaLr4q2V1q5z5N5v5J5x5Z.jpg", trailer_url: "https://www.youtube.com/watch?v=Boy4nftVfCw" },
  { title: "The Birds", year: 1963, genre: "Horror", description: "A wealthy San Francisco socialite pursues a potential boyfriend to a small Northern California town that slowly takes a turn for the bizarre when birds of all kinds suddenly begin to attack people.", duration: 119, poster_url: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", trailer_url: "https://www.youtube.com/watch?v=ydLJtKlVVZw" },
  { title: "Apocalypse Now", year: 1979, genre: "War", description: "During the Vietnam War, Captain Willard is sent on a dangerous mission into Cambodia to assassinate a renegade colonel who has set himself up as a god among a local tribe.", duration: 147, poster_url: "https://image.tmdb.org/t/p/w500/gQB8Y5RCE3e1d0LfFu6g5l3T3xZ.jpg", trailer_url: "https://www.youtube.com/watch?v=IkrhkUeDCdQ" },
  { title: "Blade Runner", year: 1982, genre: "Sci-Fi", description: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.", duration: 117, poster_url: "https://image.tmdb.org/t/p/w500/63N9uy8ndLhjlJ3tg1JX3vYk5hZ.jpg", trailer_url: "https://www.youtube.com/watch?v=eogpIG53Cis" },
  { title: "Taxi Driver", year: 1976, genre: "Crime", description: "A mentally unstable veteran works as a nighttime taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action.", duration: 114, poster_url: "https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a95Op0iT.jpg", trailer_url: "https://www.youtube.com/watch?v=UUxD4-dEzn0" },
  { title: "Raging Bull", year: 1980, genre: "Drama", description: "The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.", duration: 129, poster_url: "https://image.tmdb.org/t/p/w500/8l4P8Q7X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Deer Hunter", year: 1978, genre: "War", description: "An in-depth examination of how the Vietnam War affects the lives of people in a small industrial town in Pennsylvania.", duration: 183, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975, genre: "Drama", description: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.", duration: 133, poster_url: "https://image.tmdb.org/t/p/w500/3jcbDmRFiQ83drXNOvRDeKHxS0y.jpg", trailer_url: "https://www.youtube.com/watch?v=OXrcDonY-B8" },
  { title: "Chinatown", year: 1974, genre: "Mystery", description: "A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption, and murder.", duration: 130, poster_url: "https://image.tmdb.org/t/p/w500/iQbVIAuO23nHoa11JwY5Z5X5X5X.jpg", trailer_url: "https://www.youtube.com/watch?v=TQj0z0j0z0j" },
  { title: "The Conversation", year: 1974, genre: "Thriller", description: "A paranoid, secretive surveillance expert has a crisis of conscience when he suspects that a couple he is spying on will be murdered.", duration: 113, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Network", year: 1976, genre: "Drama", description: "A television network cynically exploits a deranged former anchor's ravings and revelations about the media for their own profit.", duration: 121, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Rocky", year: 1976, genre: "Drama", description: "A small-time Philadelphia boxer gets a supremely rare chance to fight the world heavyweight champion in a bout in which he strives to go the distance for his self-respect.", duration: 120, poster_url: "https://image.tmdb.org/t/p/w500/9TUR3s1PMJHwDRbpm7PWQ0S7irY.jpg", trailer_url: "https://www.youtube.com/watch?v=3VUblDwa648" },
  { title: "Annie Hall", year: 1977, genre: "Comedy", description: "Neurotic New York comedian Alvy Singer falls in love with the ditzy Annie Hall.", duration: 93, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Sting", year: 1973, genre: "Crime", description: "In 1930s Chicago, a young con man seeking revenge for his murdered partner teams up with a master of the big con to win a fortune from a criminal banker.", duration: 129, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The French Connection", year: 1971, genre: "Crime", description: "A pair of NYC cops in the Narcotics Bureau stumble onto a drug smuggling job with a French connection.", duration: 104, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Butch Cassidy and the Sundance Kid", year: 1969, genre: "Western", description: "Wyoming, early 1900s. Butch Cassidy and The Sundance Kid are the leaders of a band of outlaws.", duration: 110, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Midnight Cowboy", year: 1969, genre: "Drama", description: "A naive hustler travels from Texas to New York to seek personal fortune, finding a new friend in the process.", duration: 113, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Easy Rider", year: 1969, genre: "Drama", description: "Two counterculture bikers travel from Los Angeles to New Orleans in search of America.", duration: 95, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Wild Bunch", year: 1969, genre: "Western", description: "An aging group of outlaws look for one last big score as the 'traditional' American West is disappearing around them.", duration: 145, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "2001: A Space Odyssey", year: 1968, genre: "Sci-Fi", description: "Humanity finds a mysterious object buried beneath the lunar surface and sets off to find its origins with the help of HAL 9000.", duration: 149, poster_url: "https://image.tmdb.org/t/p/w500/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg", trailer_url: "https://www.youtube.com/watch?v=oR_e9y-bka0" },
  { title: "Planet of the Apes", year: 1968, genre: "Sci-Fi", description: "An astronaut crew crash-lands on a planet in the distant future where intelligent talking apes are the dominant species.", duration: 112, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Sound of Music", year: 1965, genre: "Musical", description: "A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower.", duration: 174, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Dr. Strangelove", year: 1964, genre: "Comedy", description: "An insane general triggers a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.", duration: 95, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "To Kill a Mockingbird", year: 1962, genre: "Drama", description: "Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge.", duration: 129, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "West Side Story", year: 1961, genre: "Musical", description: "Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.", duration: 153, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Some Like It Hot", year: 1959, genre: "Comedy", description: "After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women.", duration: 121, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Vertigo", year: 1958, genre: "Mystery", description: "A former police detective juggles wrestling with his personal demons and becoming obsessed with a hauntingly beautiful woman.", duration: 128, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "12 Angry Men", year: 1957, genre: "Drama", description: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.", duration: 96, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Rear Window", year: 1954, genre: "Mystery", description: "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.", duration: 112, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Sunset Boulevard", year: 1950, genre: "Drama", description: "A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.", duration: 110, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "All About Eve", year: 1950, genre: "Drama", description: "An ingenue insinuates herself into the company of an established but aging stage actress and her circle of theater friends.", duration: 138, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Third Man", year: 1949, genre: "Mystery", description: "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend.", duration: 93, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "It's a Wonderful Life", year: 1946, genre: "Drama", description: "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.", duration: 130, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Double Indemnity", year: 1944, genre: "Crime", description: "An insurance representative lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator's suspicions.", duration: 107, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Maltese Falcon", year: 1941, genre: "Mystery", description: "A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.", duration: 100, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Modern Times", year: 1936, genre: "Comedy", description: "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.", duration: 87, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "City Lights", year: 1931, genre: "Comedy", description: "With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.", duration: 87, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The General", year: 1926, genre: "Comedy", description: "When Union spies steal an engineer's beloved locomotive, he pursues it single-handedly and straight through enemy lines.", duration: 78, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "The Kid", year: 1921, genre: "Comedy", description: "The Tramp cares for an abandoned child, but events put their relationship in jeopardy.", duration: 68, poster_url: "https://image.tmdb.org/t/p/w500/5X5X5X5X5X5X5X5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=yUp6d79WRVI" },
  { title: "Interstellar", year: 2014, genre: "Sci-Fi", description: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel.", duration: 169, poster_url: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailer_url: "https://www.youtube.com/watch?v=zSWdZVtXT7E" },
  { title: "Mad Max: Fury Road", year: 2015, genre: "Action", description: "In a post-apocalyptic wasteland, Max teams up with a mysterious woman, Furiosa, to try and survive.", duration: 120, poster_url: "https://image.tmdb.org/t/p/w500/hA2ple9q4mMD3Yg5fLaRf1me8s4.jpg", trailer_url: "https://www.youtube.com/watch?v=hEJnMQG9ev8" },
  { title: "Django Unchained", year: 2012, genre: "Western", description: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", duration: 165, poster_url: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkW1DqH.jpg", trailer_url: "https://www.youtube.com/watch?v=eUdM9vrCbow" },
  { title: "The Revenant", year: 2015, genre: "Adventure", description: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead.", duration: 156, poster_url: "https://image.tmdb.org/t/p/w500/ji3ecJphATlJgqDY6iPL3g3Uaiz.jpg", trailer_url: "https://www.youtube.com/watch?v=LoebZZ8K5N0" },
  { title: "Birdman", year: 2014, genre: "Comedy", description: "A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.", duration: 119, poster_url: "https://image.tmdb.org/t/p/w500/ngl2FKBlU3fIHxq5BH0P5aXpc3N.jpg", trailer_url: "https://www.youtube.com/watch?v=uJfLoE6hanc" },
  { title: "12 Years a Slave", year: 2013, genre: "Drama", description: "In the pre-Civil War United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.", duration: 134, poster_url: "https://image.tmdb.org/t/p/w500/xdANQijuNrJaw1HA61rDccME4Tm.jpg", trailer_url: "https://www.youtube.com/watch?v=z02Ie8wKKRg" },
  { title: "Gravity", year: 2013, genre: "Sci-Fi", description: "Two astronauts work together to survive after an accident leaves them stranded in space.", duration: 91, poster_url: "https://image.tmdb.org/t/p/w500/uIttJ8g1akv3y6J3pI9Y1hAS0WC.jpg", trailer_url: "https://www.youtube.com/watch?v=OiTiKOy59o4" },
  { title: "Her", year: 2013, genre: "Romance", description: "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.", duration: 126, poster_url: "https://image.tmdb.org/t/p/w500/7a4s6fK3xZ7j8Z7j8Z7j8Z7j8Z7j.jpg", trailer_url: "https://www.youtube.com/watch?v=ne6p6Wf4lG8" },
  { title: "The Grand Budapest Hotel", year: 2014, genre: "Comedy", description: "The adventures of Gustave H, a legendary concierge at a famous hotel, and Zero Moustafa, the lobby boy who becomes his most trusted friend.", duration: 99, poster_url: "https://image.tmdb.org/t/p/w500/nX5XotM9yprCKarRH4fzOq1vm1q.jpg", trailer_url: "https://www.youtube.com/watch?v=1Fg5iWmQjwk" },
  { title: "La La Land", year: 2016, genre: "Musical", description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", duration: 128, poster_url: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg", trailer_url: "https://www.youtube.com/watch?v=0pdqf4P9MB8" },
  { title: "Arrival", year: 2016, genre: "Sci-Fi", description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", duration: 116, poster_url: "https://image.tmdb.org/t/p/w500/hLudzvGfpi6JlwUnsNhXwKKg4j.jpg", trailer_url: "https://www.youtube.com/watch?v=tFMo3UJ4B4g" },
  { title: "Blade Runner 2049", year: 2017, genre: "Sci-Fi", description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.", duration: 164, poster_url: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWj5fU5Nby0Yq5n.jpg", trailer_url: "https://www.youtube.com/watch?v=gCcx85zbxz4" },
  { title: "Dunkirk", year: 2017, genre: "War", description: "Allied soldiers from Belgium, the British Empire and France are surrounded by the German Army and evacuated during a fierce battle in World War II.", duration: 106, poster_url: "https://image.tmdb.org/t/p/w500/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg", trailer_url: "https://www.youtube.com/watch?v=F-eMt3SrfFU" },
  { title: "Three Billboards Outside Ebbing, Missouri", year: 2017, genre: "Crime", description: "A mother personally challenges the local authorities to solve her daughter's murder when they fail to catch the culprit.", duration: 115, poster_url: "https://image.tmdb.org/t/p/w500/vgGVe9W5z99aPxjoqLj0w9K9EnY.jpg", trailer_url: "https://www.youtube.com/watch?v=Jit3YhGx5pU" },
  { title: "Call Me by Your Name", year: 2017, genre: "Romance", description: "In 1980s Italy, romance blossoms between a seventeen-year-old student and the older man hired as his father's research assistant.", duration: 132, poster_url: "https://image.tmdb.org/t/p/w500/rtn5NTy8XYlBdsy7J2Qn52I05bJ.jpg", trailer_url: "https://www.youtube.com/watch?v=Z9AYPxH5NTM" },
  { title: "The Shape of Water", year: 2017, genre: "Fantasy", description: "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature.", duration: 123, poster_url: "https://image.tmdb.org/t/p/w500/k4FwHlMhuRR5BISY2Gm2QZHlH5Q.jpg", trailer_url: "https://www.youtube.com/watch?v=XFYWazblaUA" },
  { title: "Black Panther", year: 2018, genre: "Action", description: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.", duration: 134, poster_url: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg", trailer_url: "https://www.youtube.com/watch?v=xjDjIWPwcPU" },
  { title: "A Star Is Born", year: 2018, genre: "Drama", description: "A musician helps a young singer find fame as age and alcoholism send his own career into a downward spiral.", duration: 136, poster_url: "https://image.tmdb.org/t/p/w500/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg", trailer_url: "https://www.youtube.com/watch?v=nSbzyEJ8X9E" },
  { title: "Bohemian Rhapsody", year: 2018, genre: "Drama", description: "The story of the legendary rock band Queen and lead singer Freddie Mercury, leading up to their famous performance at Live Aid.", duration: 134, poster_url: "https://image.tmdb.org/t/p/w500/lHu1wtNdhqKNHvq16k9o6n2B8rC.jpg", trailer_url: "https://www.youtube.com/watch?v=mP0VHJYFOAU" },
  { title: "Roma", year: 2018, genre: "Drama", description: "A year in the life of a middle-class family's maid in Mexico City in the early 1970s.", duration: 135, poster_url: "https://image.tmdb.org/t/p/w500/6Xsz9a7vqZL1x3x0jvcv6y5h2FJ.jpg", trailer_url: "https://www.youtube.com/watch?v=6BS27ngZtxg" },
  { title: "Joker", year: 2019, genre: "Crime", description: "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City.", duration: 122, poster_url: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", trailer_url: "https://www.youtube.com/watch?v=zAGVQLHvwOY" },
  { title: "1917", year: 2019, genre: "War", description: "April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message.", duration: 119, poster_url: "https://image.tmdb.org/t/p/w500/iZf0uY3mzGJ3SfFV5D9d9oY9I9x.jpg", trailer_url: "https://www.youtube.com/watch?v=YqNYrYUiMfg" },
  { title: "Once Upon a Time in Hollywood", year: 2019, genre: "Comedy", description: "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age.", duration: 161, poster_url: "https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg", trailer_url: "https://www.youtube.com/watch?v=ELeMaP8EPAA" },
  { title: "The Irishman", year: 2019, genre: "Crime", description: "Hitman Frank Sheeran looks back at the secrets he kept as a loyal member of the Bufalino crime family.", duration: 209, poster_url: "https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg", trailer_url: "https://www.youtube.com/watch?v=WHXxVmeGQUc" },
  { title: "Nomadland", year: 2020, genre: "Drama", description: "A woman in her sixties embarks on a journey through the American West after losing everything in the Great Recession.", duration: 108, poster_url: "https://image.tmdb.org/t/p/w500/6pqn1d4Cx6pY2DpJfJqF6Z9Y9Z9.jpg", trailer_url: "https://www.youtube.com/watch?v=6sxCFZ8_d84" },
  { title: "Dune", year: 2021, genre: "Sci-Fi", description: "Paul Atreides leads a rebellion to restore his family's name while navigating a dangerous planet.", duration: 155, poster_url: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", trailer_url: "https://www.youtube.com/watch?v=8g18jFHCLXk" },
  { title: "The Power of the Dog", year: 2021, genre: "Drama", description: "A domineering rancher responds with mocking cruelty when his brother brings home a new wife and her son.", duration: 126, poster_url: "https://image.tmdb.org/t/p/w500/kEy48iCzGnp8ao1cRZh5Eq7pU1b.jpg", trailer_url: "https://www.youtube.com/watch?v=Mu1K7cGj2RM" },
  { title: "Everything Everywhere All at Once", year: 2022, genre: "Action", description: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her.", duration: 139, poster_url: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVln5JlZX58FX9f.jpg", trailer_url: "https://www.youtube.com/watch?v=wxN1T1uxKV2" },
  { title: "Top Gun: Maverick", year: 2022, genre: "Action", description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, training a new generation of pilots.", duration: 130, poster_url: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg", trailer_url: "https://www.youtube.com/watch?v=giXco2jaZ_4" },
  { title: "The Banshees of Inisherin", year: 2022, genre: "Comedy", description: "Two lifelong friends find themselves at an impasse when one abruptly ends their relationship.", duration: 114, poster_url: "https://image.tmdb.org/t/p/w500/4y2fN1F7Q0dO3J4GmD5Z5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=InYf7jQz_0Q" },
  { title: "Oppenheimer", year: 2023, genre: "Drama", description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", duration: 180, poster_url: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", trailer_url: "https://www.youtube.com/watch?v=uYPbbksJxIg" },
  { title: "Barbie", year: 2023, genre: "Comedy", description: "Barbie suffers a crisis that leads her to question her world and her existence.", duration: 114, poster_url: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", trailer_url: "https://www.youtube.com/watch?v=pBk4NYhWNMM" },
  { title: "Killers of the Flower Moon", year: 2023, genre: "Crime", description: "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one.", duration: 206, poster_url: "https://image.tmdb.org/t/p/w500/aZXHjmhSS3R4jhlWv5x5p0n2p0n.jpg", trailer_url: "https://www.youtube.com/watch?v=EP34Yoxs3FQ" },
  { title: "Poor Things", year: 2023, genre: "Comedy", description: "The incredible tale of the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.", duration: 141, poster_url: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg", trailer_url: "https://www.youtube.com/watch?v=RlbR5N6veqw" },
  { title: "The Zone of Interest", year: 2023, genre: "Drama", description: "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig strive to build a dream life for their family.", duration: 105, poster_url: "https://image.tmdb.org/t/p/w500/hU2q2XQl7y5N5Y1q5X5X5X5X5X5.jpg", trailer_url: "https://www.youtube.com/watch?v=U4RDCKRJ3DM" },
];

async function populateMovies() {
  try {
    console.log("🔄 Starting to populate movies...");
    
    // Check existing movies
    const existingMovies = await query("SELECT title, year FROM movies");
    const existingSet = new Set(existingMovies.rows.map(m => `${m.title}_${m.year}`));
    
    // Filter out movies that already exist
    const moviesToAdd = popularMovies.filter(m => !existingSet.has(`${m.title}_${m.year}`));
    
    if (moviesToAdd.length === 0) {
      console.log(`ℹ️  All movies already exist in database (${existingMovies.rows.length} movies).`);
      return;
    }

    console.log(`📝 Adding ${moviesToAdd.length} new movies (${existingMovies.rows.length} already exist)...`);

    // Insert movies that don't exist
    let added = 0;
    for (const movie of moviesToAdd) {
      try {
        await query(
          `INSERT INTO movies (title, year, genre, description, duration, poster_url, trailer_url)
           VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [movie.title, movie.year, movie.genre, movie.description, movie.duration, movie.poster_url, movie.trailer_url]
        );
        added++;
      } catch (error) {
        // Skip if duplicate or other error
        console.log(`⚠️  Skipped ${movie.title} (${error.message})`);
      }
    }

    console.log(`✅ Successfully added ${added} new movies to the database!`);
    console.log(`📊 Total movies in database: ${existingMovies.rows.length + added}`);
  } catch (error) {
    console.error("❌ Error populating movies:", error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  populateMovies()
    .then(() => {
      console.log("✅ Movie population complete!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("❌ Movie population failed:", error);
      process.exit(1);
    });
}

module.exports = { populateMovies };

