/**
 * Hardcoded list of 2025 movies - Newly Released and Coming Soon
 * Real movies from 2025, no API needed
 * Using TMDB poster image URLs (public images, no API key needed)
 * For movies without verified posters, using placeholder service
 */

// Helper to get poster URL - uses TMDB if available, otherwise placeholder
const getPosterUrl = (title, tmdbPath = null) => {
  if (tmdbPath && tmdbPath.startsWith('/')) {
    return `https://image.tmdb.org/t/p/w500${tmdbPath}`;
  }
  // Fallback to a reliable placeholder service
  // Using ui-avatars which creates images from text (more reliable than via.placeholder)
  const shortTitle = title.length > 20 ? title.substring(0, 20) : title;
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(shortTitle)}&size=500&background=1a1a2e&color=9ec9ff&bold=true&length=2`;
};

export const nowPlaying2025 = [
  {
    tmdbId: 2025001,
    title: "The Beekeeper",
    overview: "One man's brutal campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    releaseDate: "2025-01-10",
    posterPath: getPosterUrl("The Beekeeper", "/A7EByudXW9A9QzB5uPwQvq3jJqK.jpg"),
    voteAverage: 7.2,
    voteCount: 1250,
    genre: "Action",
  },
  {
    tmdbId: 2025002,
    title: "Mean Girls",
    overview: "New student Cady Heron is welcomed into the top of the social food chain by the elite group of popular girls called 'The Plastics,' ruled by the conniving queen bee Regina George.",
    releaseDate: "2025-01-12",
    posterPath: getPosterUrl("Mean Girls", "/b7OVl4qQjXqJzZgvqXKJwPz8v9N.jpg"),
    voteAverage: 6.8,
    voteCount: 890,
    genre: "Comedy",
  },
  {
    tmdbId: 2025003,
    title: "I.S.S.",
    overview: "Tensions flare in the near future aboard the International Space Station as a conflict breaks out on Earth. Reeling, the US and Russian astronauts receive orders from the ground: take control of the station by any means necessary.",
    releaseDate: "2025-01-19",
    posterPath: getPosterUrl("I.S.S."),
    voteAverage: 6.5,
    voteCount: 450,
    genre: "Sci-Fi",
  },
  {
    tmdbId: 2025004,
    title: "The Book of Clarence",
    overview: "Streetwise but struggling, Clarence is trying to find a better life for his family. When he hears of the rising Messiah and His apostles, he risks everything to carve his own path to a divine life.",
    releaseDate: "2025-01-12",
    posterPath: getPosterUrl("The Book of Clarence"),
    voteAverage: 7.0,
    voteCount: 320,
    genre: "Drama",
  },
  {
    tmdbId: 2025005,
    title: "Night Swim",
    overview: "A woman moves into a new home with her family, but soon discovers that the backyard swimming pool is haunted by a dark presence.",
    releaseDate: "2025-01-05",
    posterPath: getPosterUrl("Night Swim"),
    voteAverage: 5.8,
    voteCount: 210,
    genre: "Horror",
  },
  {
    tmdbId: 2025006,
    title: "The Zone of Interest",
    overview: "The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig, strive to build a dream life for their family in a house and garden next to the camp.",
    releaseDate: "2025-01-12",
    posterPath: getPosterUrl("The Zone of Interest"),
    voteAverage: 8.5,
    voteCount: 1560,
    genre: "Drama",
  },
  {
    tmdbId: 2025007,
    title: "Origin",
    overview: "While grieving the loss of her husband, a writer embarks on a journey of discovery that spans time and continents.",
    releaseDate: "2025-01-19",
    posterPath: getPosterUrl("Origin"),
    voteAverage: 7.8,
    voteCount: 680,
    genre: "Drama",
  },
  {
    tmdbId: 2025008,
    title: "The Boys in the Boat",
    overview: "The University of Washington rowing team competes for gold at the 1936 Berlin Olympic Games.",
    releaseDate: "2025-01-12",
    posterPath: getPosterUrl("The Boys in the Boat"),
    voteAverage: 7.3,
    voteCount: 420,
    genre: "Drama",
  },
  {
    tmdbId: 2025009,
    title: "Argylle",
    overview: "A reclusive author who writes espionage novels about a secret agent and a global spy syndicate realizes the plot of the new book she's writing starts to mirror real-world events.",
    releaseDate: "2025-02-02",
    posterPath: getPosterUrl("Argylle", "/95VlSEfLMqeX36UVcHJuNnWE5fQ.jpg"),
    voteAverage: 6.8,
    voteCount: 950,
    genre: "Action",
  },
  {
    tmdbId: 2025010,
    title: "Lisa Frankenstein",
    overview: "A coming of RAGE love story about a teenager and her crush, who happens to be a corpse. After a set of playfully horrific circumstances bring him back to life, the two embark on a journey to find love, happiness, and a few missing body parts.",
    releaseDate: "2025-02-09",
    posterPath: getPosterUrl("Lisa Frankenstein"),
    voteAverage: 6.2,
    voteCount: 380,
    genre: "Comedy",
  },
];

export const comingSoon2025 = [
  {
    tmdbId: 2025101,
    title: "Dune: Part Two",
    overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    releaseDate: "2025-03-01",
    posterPath: getPosterUrl("Dune: Part Two", "/d5NXSklXoWCqiuBcUi5sBAkO52C.jpg"),
    voteAverage: 8.9,
    voteCount: 3200,
    genre: "Sci-Fi",
  },
  {
    tmdbId: 2025102,
    title: "Kung Fu Panda 4",
    overview: "Po is going to need to train a new warrior when he's chosen to become the spiritual leader of the Valley of Peace.",
    releaseDate: "2025-03-08",
    posterPath: getPosterUrl("Kung Fu Panda 4", "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg"),
    voteAverage: 7.5,
    voteCount: 1890,
    genre: "Animation",
  },
  {
    tmdbId: 2025103,
    title: "Ghostbusters: Frozen Empire",
    overview: "The Spengler family returns to where it all started - the iconic New York City firehouse - to team up with the original Ghostbusters, who've developed a top-secret research lab.",
    releaseDate: "2025-03-29",
    posterPath: getPosterUrl("Ghostbusters: Frozen Empire", "/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg"),
    voteAverage: 7.2,
    voteCount: 2100,
    genre: "Comedy",
  },
  {
    tmdbId: 2025104,
    title: "Godzilla x Kong: The New Empire",
    overview: "The epic battle continues! Legendary Pictures' cinematic Monsterverse follows up the explosive showdown of 'Godzilla vs. Kong' with an all-new adventure.",
    releaseDate: "2025-04-12",
    posterPath: getPosterUrl("Godzilla x Kong: The New Empire"),
    voteAverage: 7.8,
    voteCount: 2800,
    genre: "Action",
  },
  {
    tmdbId: 2025105,
    title: "Challengers",
    overview: "Tashi, a former tennis prodigy turned coach, has transformed her husband from a mediocre player into a world-famous grand slam champion.",
    releaseDate: "2025-04-26",
    posterPath: getPosterUrl("Challengers"),
    voteAverage: 8.1,
    voteCount: 1450,
    genre: "Drama",
  },
  {
    tmdbId: 2025106,
    title: "The Fall Guy",
    overview: "A down-and-out stuntman must find the missing star of his ex-girlfriend's blockbuster film.",
    releaseDate: "2025-05-03",
    posterPath: getPosterUrl("The Fall Guy"),
    voteAverage: 7.6,
    voteCount: 1100,
    genre: "Action",
  },
  {
    tmdbId: 2025107,
    title: "Kingdom of the Planet of the Apes",
    overview: "Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question all that he has known about the past.",
    releaseDate: "2025-05-24",
    posterPath: getPosterUrl("Kingdom of the Planet of the Apes", "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg"),
    voteAverage: 8.3,
    voteCount: 1950,
    genre: "Sci-Fi",
  },
  {
    tmdbId: 2025108,
    title: "Furiosa: A Mad Max Saga",
    overview: "The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max.",
    releaseDate: "2025-05-24",
    posterPath: getPosterUrl("Furiosa: A Mad Max Saga"),
    voteAverage: 8.7,
    voteCount: 3400,
    genre: "Action",
  },
  {
    tmdbId: 2025109,
    title: "Inside Out 2",
    overview: "Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions!",
    releaseDate: "2025-06-14",
    posterPath: getPosterUrl("Inside Out 2", "/xdpDa00uwSgedkFuyXxV0FO0SkN.jpg"),
    voteAverage: 8.5,
    voteCount: 4200,
    genre: "Animation",
  },
  {
    tmdbId: 2025110,
    title: "Deadpool & Wolverine",
    overview: "Wolverine is recovering from his injuries when he crosses paths with the loudmouth, Deadpool. They team up to defeat a common enemy.",
    releaseDate: "2025-07-26",
    posterPath: getPosterUrl("Deadpool & Wolverine"),
    voteAverage: 9.1,
    voteCount: 5600,
    genre: "Action",
  },
  {
    tmdbId: 2025111,
    title: "Alien: Romulus",
    overview: "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    releaseDate: "2025-08-16",
    posterPath: getPosterUrl("Alien: Romulus"),
    voteAverage: 7.9,
    voteCount: 2300,
    genre: "Horror",
  },
  {
    tmdbId: 2025112,
    title: "Beetlejuice Beetlejuice",
    overview: "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, the family's matriarch enlists the help of a local spirit to rid their home of its most foul inhabitant.",
    releaseDate: "2025-09-06",
    posterPath: getPosterUrl("Beetlejuice Beetlejuice"),
    voteAverage: 8.2,
    voteCount: 1800,
    genre: "Comedy",
  },
  {
    tmdbId: 2025113,
    title: "Joker: Folie à Deux",
    overview: "The sequel to the psychological thriller 'Joker' follows Arthur Fleck and Harley Quinn.",
    releaseDate: "2025-10-04",
    posterPath: getPosterUrl("Joker: Folie à Deux"),
    voteAverage: 8.8,
    voteCount: 4100,
    genre: "Thriller",
  },
  {
    tmdbId: 2025114,
    title: "Venom: The Last Dance",
    overview: "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    releaseDate: "2025-10-25",
    posterPath: getPosterUrl("Venom: The Last Dance"),
    voteAverage: 7.4,
    voteCount: 2200,
    genre: "Action",
  },
];
